### ISSUE TITLE
NewsBusters

### ISSUE THREAD

**Issue by dylanrees** [BigMcLargeHuge/opensources#15]
http://www.newsbusters.org

Strong bias.

**Comment by BigMcLargeHuge** [comment]
Thanks for the suggestion.  Have you tried submitting it [on our website?](http://opensources.co)

**Comment by dylanrees** [comment]
Is the link at http://www.opensources.co/submissions/new ?  Looks like it's not working right now.  Also, I wasn't sure what the submission link was until I check the Gitter conversation, so it might be helpful to highlight that more clearly on the OpenSources main page.

**Comment by BigMcLargeHuge** [comment]
@dylanrees good of you to point out that it's not on our main page.  I'll add that right now.  I'm guessing that you didn't sign in and that's why you got the error.  I've added a sign-in redirect so feel free to give it a try now.

**Comment by dylanrees** [comment]
Ah yes, that works.  Thanks!
