### ISSUE TITLE
Add contribution guidelines

### ISSUE THREAD

**Issue by uncompiled** [BigMcLargeHuge/opensources#16]
In reference to #15, the preferred process for contributing to the data is not clear.

Since this repo is on GitHub, it feels natural to submit issues and PRs, but if the website is the desired entrypoint for data submissions, it would be helpful to clarify this.

Some suggestions:
- Add a link to [opensources](http://www.opensources.co/) in the project settings. This way, people that stumble on the repo can follow the link to the website.
- Add a [CONTRIBUTING.md](https://github.com/blog/1184-contributing-guidelines) to the repo that outlines the preferred process.  This would help keep the project organized because it will also display a notification about the contribution guidelines when an issue or PR is created.

**Comment by BigMcLargeHuge** [comment]
Very fair point.  A link to opensources has been added in the readme and I'll add a contributing.md.

**Comment by BigMcLargeHuge** [comment]
Contributing.md is added.  Thanks for the suggestion.
