### ISSUE TITLE
Add a 'bias' field

### ISSUE THREAD

**Issue by vlidholt** [BigMcLargeHuge/opensources#21]
For many applications having a 'bias' field associated with each news site would be useful. E.g. left/right wing, but perhaps also something like east/west.

**Comment by BigMcLargeHuge** [comment]
Hi Viktor, thanks for the suggestion.  We've played around with this idea but have decided that it would be best to avoid assessing the political leanings of any particular source.  There are many dimensions that could be analized but, given our current resources and the scale of the undertaking, it seems best to stick with tagging issues relating to a source's credibility for the time being.
