### ISSUE TITLE
Submit form returns a 505 error.

### ISSUE THREAD

**Issue by tomatell** [BigMcLargeHuge/opensources#3]
The submit form returns a 505 error. The following screenshot shows the details.
<img width="1013" alt="screen shot 2016-12-20 at 09 44 11" src="https://cloud.githubusercontent.com/assets/1432263/21364594/ce6c2356-c6f1-11e6-916a-cad8d0560c8a.png">

**Comment by BigMcLargeHuge** [comment]
Should be resolved, feel free to try again.
