### ISSUE TITLE
site wrongfully included/poorly labelled

### ISSUE THREAD

**Issue by justpaladone** [BigMcLargeHuge/opensources#4]
hi, i wanted to contest http://fusion.net/ being included in your list.  Specifically for reasons of "satire", which is what it appears to be listed as.  I have double-checked their news page and it currently has all news stories that I have seen elsewhere, as well as links to their sources.  This is not a satire site, though they may ocassionally have satire posts in their non-news sections.

**Comment by BigMcLargeHuge** [comment]
Error is fixed.
