### ISSUE TITLE
Typos in files

### ISSUE THREAD

**Issue by joaoe** [BigMcLargeHuge/opensources#9]
Howdy.
Look what I found
```
  "BB4SP.com" : {
    "type" : "conpiracy",
  },
```
Perhaps would be good to have a script sanitizing the json/CSV files: sorting lines, finding typos. If the files are sorted, then merge conflicts will be less.
Cheers.

**Comment by uncompiled** [comment]
I agree.  If [opensources.co](http://www.opensources.co/) is to be successful, it would be good to have scripts and the method to reproduce this data.

**Comment by BigMcLargeHuge** [comment]
Should be resolved.  Regarding the reproduction of data, we now have a pretty solid script in place that generates the json file.  But please do let us know if you find any other bugs.
